# Generated by Django 3.0.6 on 2020-07-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('heading0', models.CharField(default='', max_length=50)),
                ('content0', models.CharField(default='', max_length=50)),
                ('heading1', models.CharField(default='', max_length=50)),
                ('content1', models.CharField(default='', max_length=50)),
                ('pub_date', models.DateTimeField()),
                ('thumbnail', models.ImageField(default='', upload_to='blog/images')),
            ],
        ),
    ]
